title: Sinne van der Veer
description: Agricultural Economics, Data Science and Machine Learning
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Github: https://github.com/sinnevdveer/
